services:
  - type: web
    name: portfolio
    env: docker
    plan: free
    branch: main  # Adjust if your branch is different (e.g. master)
    dockerfilePath: ./Dockerfile
    context: .
    autoDeploy: true
